### ISSUE TITLE
Add tox testing support for snowflake, redshift and bigquery

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-codegen#185]
```[tasklist]
### Tasks
- [ ] https://github.com/dbt-labs/dbt-codegen/issues/200
- [ ] https://github.com/dbt-labs/dbt-codegen/issues/201
- [ ] https://github.com/dbt-labs/dbt-codegen/issues/202
```

### Describe the feature
Add support for testing the following adapters with tox.

- dbt-snowflake
- dbt-redshift
- dbt-bigquery

This will entail:
- modify profiles.yml to meet the desired var format (example in [dbt-package-testing](https://github.com/dbt-labs/dbt-package-testing/blob/main/integration_tests/profiles.yml))
- add the adapters to supported_adapters.env
- add commands to tox.ini for the adapter tests
- pass through the env vars to .github/workflows/ci.yml

### Describe alternatives you've considered
Not adding other adapter support

### Additional context
This work is related to issue #183.  Postgres testing support was added in #181.

#184 is a blocker for supporting redshift.

The package will need to be released again after this testing is added before it will run in dbt CI.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

Optionally, part of this work might be to also remove CircleCI and go down to just using GitHub actions to run the same tests.
